#Ben Zaloga
#STAT 1129
#Homework 6

#Question 1
```{r}
m1 <- matrix(c(7,9,12,2,4,13), byrow=TRUE, nrow = 2)
m2 <- matrix(c(1,7,12,19,2,8,13,20,3,9,14,21), byrow=TRUE, nrow = 3)
m1 %*% m2
```

#Question 2
```{r}
dataFrame <- data.frame (
  id = c(1:5),
  name = c('Ben', 'Jack', 'Steven', 'Mike', 'Doc'),
  salary = c(1000, 690, 420, 750, 250)
)

dept <- cbind(dataFrame, department = c('investment banking', 'sales & trading', 'marketing', 'investor relations', 'customer service'))

rem <- dept[c(1, 3, 5), c(2, 3)]

dataFrame
dept
rem

new.dataFrame <- dataFrame[c(1, 4, 5),]
barplot(new.dataFrame$salary, names.arg = new.dataFrame$name)
pie(c(max(dataFrame$salary), min(dataFrame$salary), median(dataFrame$salary)), labels = dataFrame$name, main = 'Salary Comparison Among Co-Workers')
```
#Question 3: Function 1, Welcome / Start
```{r}

start = ''

'Welcome to Rock, Paper, Scissors!'

while (start != 'y' & start != 'n') {
  start <- readline(prompt = 'Are you ready to play? (y/n): ')
  start <- tolower(start)
}
if (start == 'y') {
  'Starting Game...'
} else {
  'Come Back Soon!'
}
```

#Question 3: Function 2, Outcome / Decision
# I just outlined the basics of how this function works for the sample player move 'r' and a random choice by the computer, as setting up the remainder of the function builds off of the same idea, running through each possible outcome
```{r}
player_move = 'r'
options = c('r', 'p', 's')
computer_move = sample(options, 1)

if (player_move == computer_move) {
  'tie - computer chose rock'
} else if ((player_move == 'r')&(computer_move == 'p')) {
    'loss - computer chose paper'
} else if ((player_move == 'r')&(computer_move == 's')) {
    'win - computer chose scissors'
}
```